name: face_benchmark
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pip
  - pip:
      - opencv-python>=4.5.3
      - insightface>=0.6.0
      - facenet-pytorch>=2.5.2
      - tqdm>=4.62.0
      - seaborn>=0.11.1
      - pillow>=8.3.1
      - kaggle                 # For Kaggle dataset download
      